from dataclasses import dataclass  # , replace
from Role import Role

# Model

# @TODO: Criar atributo de senha temporária


@dataclass(init=True)
class User:
    """
    Entity object for the system.

    Attributes:
        user_id     uuid autogenerated (unique)
        name        String
        last_name   String
        email       String (unique)
        age         String
        role        Role object
        created_at  timestamp
        updated_at  timestamp

    """
    user_id: str = None
    name: str = None
    last_name: str = None
    email: str = None
    password: str = None
    age: str = None
    role: Role = None
    created_at: str = None
    updated_at: str = None
