from dataclasses import dataclass, field  # , replace

from DateUtils import get_current_time
from IdUtils import generate_id
from PasswUtils import generate_temp_passwd
from Role import Role

# Model


@dataclass(kw_only=True)
class SystemUser:
    """
    Entity object abstract user for the system.

    Attributes:
        user_id     uuid autogenerated (unique)
        name        String
        last_name   String
        email       String (unique)
        age         String
        role        Role object
        created_at  timestamp
        updated_at  timestamp

    """

    user_id: str = generate_id()
    name: str
    last_name: str = None
    email: str
    password: str
    age: str = None
    role: Role
    created_at: str = get_current_time()
    updated_at: str = get_current_time()


@dataclass(kw_only=True)
class Admin(SystemUser):
    """ "
    Entity admin user for the system
    """

    password: str


@dataclass(kw_only=True)
class User(SystemUser):
    """ "
    Entity user for the system
    """

    password: str = generate_temp_passwd()
